---
- name: "Create directory"
  become: true
  file:
    path: ~/udapeople/
    state: directory

- name: Copy index test page
  template:
    src: "/Users/light/Documents/practice/project3"
    dest: "."

- name: "deploy backend"
  become: true
  unarchive:
    src: artifact.tar.gz
    dest: ~/udapeople/

- name: "run backend"
  become: true
  shell: |
    cd ~/udapeople/
    npm i
    pm2 stop default
    pm2 start npm -- start
