---
- name: "Create directory"
  become: true
  file:
    path: ~/udapeople/
    state: directory

# - name: Copy index test page
#   template:
#     src: "artifact.tar.gz"
#     dest: "."

- name: "deploy backend"
  become: true
  unarchive:
    src: /etc/artifact.tar.gz
    dest: ~/udapeople/

- name: "run backend"
  become: true
  shell: |
    cd ~/udapeople/
    npm i
    pm2 stop default
    pm2 start npm -- start
